[package]
name = "kubi-ui-glium"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
glium = { git = "https://github.com/glium/glium", rev = "968fc92378caf" }
kubi-ui = { path = "../kubi-ui", no-default-features = true }
glam = "0.24"
log = "0.4"
