[package]
name = "kubi-ui-glium"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
kubi-ui = { path = "../kubi-ui", default-features = false }
#kubi-ui = { path = "../kubi-ui" }
glium = { git = "https://github.com/glium/glium", rev = "a352c667" }
glam = "0.25"
log = "0.4"
