[package]
name = "kubi"
version = "0.1.0"
edition = "2021"

[dependencies]
glium = "0.32"
image = { version = "0.24", default_features = false, features = ["png"] }
log = "0.4"
env_logger = "0.10"
strum = { version = "0.24", features = ["derive"] }
