[workspace]
members = [
  "kubi",
  "kubi-server",
  "kubi-shared",
  "kubi-logging",
  "kubi-pool",
  "kubi-ui",
  "kubi-ui-glium",
  "kubi-ui-examples"
]
default-members = ["kubi"]
resolver = "2"

[profile.release-with-debug]
inherits = "release"
debug = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 1

[profile.dev.package.uflow]
opt-level = 3

[profile.dev.package.glium]
opt-level = 3

[profile.dev.package.bracket-noise]
opt-level = 3

[profile.dev.package.rayon]
opt-level = 3
