[package]
name = "kubi"
version = "0.1.0"
edition = "2021"

[profile.dev.package.noise]
opt-level = 3

[dependencies]
glium = "0.32"
image = { version = "0.24", default_features = false, features = ["png"] }
log = "0.4"
env_logger = "0.10"
strum = { version = "0.24", features = ["derive"] }
glam = { version = "0.22", features = ["debug-glam-assert", "mint", "fast-math"] }
hashbrown = "0.13"
noise = "0.8"
rayon = "1.6"
#ordered-float = "3.4"

[features]
default = []
