[package]
name = "kubi-ui"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
hashbrown = "0.14"
nohash-hasher = "0.2"
glam = { version = "0.24", features = ["approx"] }
glium = { git = "https://github.com/glium/glium", rev = "968fc92378caf", optional = true }
fontdue = { version = "0.7", optional = true }
rect_packer = { version = "0.2.1", optional = true }
log = "0.4"

[dev-dependencies]
kubi-logging = { path = "../kubi-logging" }
glium = { git = "https://github.com/glium/glium", rev = "968fc92378caf" }
winit = "0.29"

[features]
default = ["builtin_elements", "texture_manager", "text_rendering", "builtin_font", "backend_glium"]
backend_glium = ["dep:glium"]
texture_manager = []
text_rendering = ["dep:fontdue", "texture_manager"]
builtin_font = ["text_rendering"]
builtin_elements = []
