[package]
name = "kubi-server"
version = "0.1.0"
edition = "2021"

[dependencies]
kubi-shared = { path = "../kubi-shared" }
kubi-udp = { path = "../kubi-udp" }
kubi-logging = { path = "../kubi-logging" }
log = "*"
shipyard = "0.6"
serde = "1.0"
toml = "0.7"
glam = { version = "0.22", features = ["debug-glam-assert", "fast-math"] }

[features]
default = []
unstable = ["glam/core-simd"]
