[package]
name = "kubi-logging"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
log = "0.4"

[target.'cfg(not(target_os = "android"))'.dependencies]
env_logger = "0.10"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"
