[package]
name = "kubi-shared"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.22", features = ["debug-glam-assert", "fast-math", "serde"] }
shipyard = { git = "https://github.com/leudz/shipyard", rev = "9fd2aaa32bccee29bd7fc99ccaabec950fe13ed0" }
strum = { version = "0.24", features = ["derive"] }
bincode = "2.0.0-rc"
anyhow = "1.0"
bracket-noise = "0.8"
