[package]
name = "kubi-shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.22", features = ["debug-glam-assert", "mint", "fast-math"] }
strum = { version = "0.24", features = ["derive"] }
bracket-noise = "0.8"
