name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_PROGRESS_WHEN: never

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@v1.3.0
      with:
        packages: libudev-dev
        version: 1.0
    - uses: Swatinem/rust-cache@v2.3.0
    - name: Build
      run: cargo build
        --release
        --bin kubi
        --bin kubi-server
    - name: Create artifact
      run: |
        mkdir artifact;
        cp ./target/release/kubi ./artifact;
        cp ./target/release/kubi-server ./artifact;
        cp -r ./assets ./artifact;
    - uses: actions/upload-artifact@v3
      with:
        name: linux-x64-release
        path: ./artifact/*
        if-no-files-found: error
