name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_PROGRESS_WHEN: never

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache APT packages
      uses: awalsh128/cache-apt-pkgs-action@v1.3.0
      packages: libudev-dev
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.3.0
    - name: Build
      run: cargo build
        --release
        --bin kubi
        --bin kubi-server
    - uses: actions/upload-artifact@v3
      with:
        name: linux-x64-release
        path: |
          ./target/release/kubi
          ./target/release/kubi-server
          ./assets
